# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - skr-bphome-p-as-1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://bphome.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6595cc341b2d4bd896301d1a47dba1cd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4d2b3b022cfe467ca0b93a2babc33af6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: bphome.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6595cc341b2d4bd896301d1a47dba1cd }}/webslide:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'skr-bphome-p-as-1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f2750f6e8d84c5aa22dfd7a154eb7bb }}
        images: 'bphome.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6595cc341b2d4bd896301d1a47dba1cd }}/webslide:${{ github.sha }}'